---
abstract: 'Store attachments outside the database'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ExternalStorage
no_index:
  directory:
    - inc
    - t
  package:
    - RT::Record
    - RT::ObjectCustomFieldValue
    - RT::Attachment
recommends:
  Amazon::S3: 0
  File::Dropbox: 0
requires:
  File::Path: 0
  File::Spec: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.55'
x_module_install_rtx_version: '0.36'
x_requires_rt: 4.0.22
